### ISSUE TITLE
bgpq3 does not compile on ubuntu 

### ISSUE THREAD

**Issue by job** [snar/bgpq3#11]
Any hints? Seems broken since commit d787382df03378695075dc86b9cee51d83fdfc31

```
job@irime:/tmp/t/bgpq3$ ./configure && make
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for markdown_py... no
checking for markdown2... no
checking for markdown... markdown
checking for strlcpy... no
checking for socket in -lsocket... no
checking for getaddrinfo in -lnsl... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c bgpq3.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c sx_report.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c bgpq_expander.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c sx_slentry.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c bgpq3_printer.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c sx_prefix.c
sx_prefix.c: In function ‘sx_prefix_parse’:
sx_prefix.c:56:2: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
  strlcpy(mtext, text, sizeof(mtext));
  ^
sx_prefix.c: In function ‘sx_prefix_range_parse’:
sx_prefix.c:198:2: warning: implicit declaration of function ‘isnumber’ [-Wimplicit-function-declaration]
  } else if (isnumber(d[1])) {
  ^
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c strlcpy.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c sx_maxsockbuf.c
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -o bgpq3 bgpq3.o sx_report.o bgpq_expander.o sx_slentry.o bgpq3_printer.o sx_prefix.o strlcpy.o sx_maxsockbuf.o -lnsl
sx_prefix.o: In function `sx_prefix_range_parse':
/tmp/t/bgpq3/sx_prefix.c:198: undefined reference to `isnumber'
/tmp/t/bgpq3/sx_prefix.c:201: undefined reference to `isnumber'
collect2: error: ld returned 1 exit status
make: *** [bgpq3] Error 1
```

**Comment by yeled** [comment]
this patch will fix BSD and Linux:

```c
diff --git a/sx_prefix.c b/sx_prefix.c
index 07d4e9b..df8bf43 100644
--- a/sx_prefix.c
+++ b/sx_prefix.c
@@ -195,10 +195,10 @@ sx_prefix_range_parse(struct sx_radix_tree* tree, int af, int maxlen,
 	} else if (d[1] == '+') {
 		min=p.masklen;
 		max=maxlen;
-	} else if (isnumber(d[1])) {
+	} else if (isdigit(d[1])) {
 		char* dm = NULL;
 		min = strtoul(d+1, &dm, 10);
-		if (dm && *dm == '-' && isnumber(dm[1])) {
+		if (dm && *dm == '-' && isdigit(dm[1])) {
 			max = strtoul(dm+1, NULL, 10);
 		} else if (dm && *dm) {
 			sx_report(SX_ERROR, "Unable to parse prefix-range %s\n", text);
```

But then we have warning, too:

```
sx_prefix.c: In function ‘sx_prefix_parse’:
sx_prefix.c:56:2: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
  strlcpy(mtext, text, sizeof(mtext));
  ^
```

**Comment by snar** [comment]
Fixed, thanks for reporting.
